### PR TITLE
windows cmd script, process images in folder, print time elapsed, take on anyhow dep, crop images.

### PR DESCRIPTION
**Pull request by davehorner**
windows doesn't like ' using " in the original script would be enough to make it work as another solution.  creating a .cmd file works too.

```
warning: `rust-background-removal` (bin "rust-background-removal") generated 1 warning (run `cargo fix --bin "rust-background-removal"` to apply 1 suggestion)
    Finished release [optimized] target(s) in 22.17s
     Running `target\release\rust-background-removal.exe`
Processed images\1409.jpg in 54.581 seconds
Processed images\1418.jpg in 53.612 seconds
Processed images\1419.jpg in 59.436 seconds
Processed images\1422.jpg in 60.051 seconds
Processed images\1426.jpg in 62.424 seconds
error: process didn't exit successfully: `target\release\rust-background-removal.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
^C
c:\working\rust\rust-background-removal>cargo run --release
   Compiling rust-background-removal v0.1.0 (C:\working\rust\rust-background-removal)
    Finished release [optimized] target(s) in 15.14s
     Running `target\release\rust-background-removal.exe`
Processed images\1409.jpg in 43.106 seconds
Processed images\1418.jpg in 45.201 seconds
Processed images\1419.jpg in 44.536 seconds
Processed images\1422.jpg in 43.536 seconds
Processed images\1426.jpg in 44.610 seconds
error: process didn't exit successfully: `target\release\rust-background-removal.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
^C
c:\working\rust\rust-background-removal>cargo run --release
    Blocking waiting for file lock on package cache
   Compiling rust-background-removal v0.1.0 (C:\working\rust\rust-background-removal)
    Finished release [optimized] target(s) in 17.60s
     Running `target\release\rust-background-removal.exe`
Processed images\1409.jpg in 42.096 seconds
Processed images\1418.jpg in 40.025 seconds
Processed images\1419.jpg in 46.536 seconds
Processed images\1422.jpg in 40.420 seconds
error: process didn't exit successfully: `target\release\rust-background-removal.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```
I was surprised that small (shown first, medium, then large), was slowest of the models and it was faster as the size of the model went up!  Idk if you want to take on anyhow, a dyn Error could is another solution.

I didn't see much to read on theory of operation from imgly/background-removal-js.  The online demo did not work for me.

Your code did, thanks for the code.

### CODE REVIEW

**Comment by davehorner** [comment]
I broke it while merging; not sure theres anything here really.  closing.

**Comment by dnanhkhoa** [comment]
Thank you @davehorner for the PR,

> windows doesn't like ' using " in the original script would be enough to make it work as another solution. creating a .cmd file works too.

I am understanding that replacing ' with " in download_models.sh will solve the problem on Windows right? Does Windows support running .sh file? If so, I prefer keeping the download_models.sh file so it can be used on other OS too.

**Comment by dnanhkhoa** [comment]
>I was surprised that small (shown first, medium, then large), was slowest of the models and it was faster as the size of the model went up

This's really interesting, I run my code on a 2018 Macbook pro (i7) and it took ~2-3s per image using the medium. I haven't compared inference time between 3 models yet but theoretically the smallest should be the fastest.

**Comment by davehorner** [comment]
> Thank you @davehorner for the PR,
> 
> > windows doesn't like ' using " in the original script would be enough to make it work as another solution. creating a .cmd file works too.
> 
> I am understanding that replacing ' with " in download_models.sh will solve the problem on Windows right? Does Windows support running .sh file? If so, I prefer keeping the download_models.sh file so it can be used on other OS too.


No windows does not support .sh files. I think the .cmd file is the best solution, it also is a clue that it works on windows.

**Comment by davehorner** [comment]
didn't mean to include 0234ca3 in this PR but you're welcome to it if you'd like.  could use some command line switches, didn't want to take on a dep.  do you have any additional detail about the operation I could read?  it works quite well just would like to know how it accomplishes this.

**Comment by dnanhkhoa** [comment]
> do you have any additional detail about the operation I could read? it works quite well just would like to know how it accomplishes this.

I had a look at their first issue, https://github.com/imgly/background-removal-js/issues/1. It seems like the authors don't have plan to publish the model architecture. That might be the reason why they chose the ONNX format. I think we can write a small script to print all of the layer names in the ONNX models and guess what architecture used. Anyway, my guess is that they used a U-net-based model (need to verify this).

**Comment by dnanhkhoa** [comment]
@davehorner I just dug into the model and found that the medium model uses the exact architecture mentioned in this repository: https://github.com/xuebinqin/DIS . You can also find the paper describing the technical details.

Here is the code I used to compare 2 architectures:
CleanShot 2023-09-20 at 17 04 53@2x

**Pull request closed without merging**
